
{'date': 'Wed Sep 18 2019 17:45:05.103 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 46
    Jogo()
  module <module> line 42
    self.carta.monta_baralho(self.carta)
  module <module> line 28
    carta = Carta(imagem_carta)
TypeError: __init__() takes 1 positional argument but more were given
'''},